### ISSUE TITLE
Mn change

### ISSUE THREAD

**Issue by ckrisgarrett** [ckrisgarrett/closures-2d#12]
After calculating alpha, change u so that u1=<m e^(a^Tm)> and u1_0 = u_0.

**Comment by tshaffe1** [comment]
My change is in the `mn` branch. It still runs, and the results seem to have changed by ~1e-3 or ~1e-4. After it's tested and the issue is resolved, I'll merge it into `master`

**Comment by tshaffe1** [comment]
The change in the `mn` branch delayed, but didn't prevent, the program from aborting with `Max regularization achieved`.

**Comment by tshaffe1** [comment]
I made the small change for alpha we went over on the board the other day. It improved again, but still didn't fix the issue. The correction moves the scale factor into the zeroth component of alpha, but I wasn't sure about the zeroth harmonic. Is it guaranteed to be the same at every quadrature point?
