### ISSUE TITLE
Add Lebedev Quadrature

### ISSUE THREAD

**Issue by ckrisgarrett** [ckrisgarrett/closures-2d#16]
Add Lebedev quadrature.

**Comment by tshaffe1** [comment]
I added those tests, and the Lebedev quadrature seems to be working. I also made sure that aside from initialization, both quadratures follow the same code path. The kinetic solver is still giving nonphysical output, though. An example `input.deck` and the results follow.

```
SOLVER kinetic
NUM_CELLS_X 50
NUM_CELLS_Y 50
NUM_MPI_PARTITIONS_X 1
NUM_MPI_PARTITIONS_Y 1
A_X -1.5
B_X 1.5
A_Y -1.5
B_Y 1.5
T_FINAL 1.0
OUT_DELTA_T 1000.1
GAUSSIAN_SIGMA 0.0
FLOOR 1e-4
INIT_COND 0
SIGMA 1.0
USE_LEBEDEV ?
QUAD_ORDER 12
CFL_FACTOR 0.9
```

![gauss](https://cloud.githubusercontent.com/assets/6613013/8706519/2a716b16-2afe-11e5-9184-ddbd2f30d36d.png)
![lebedev](https://cloud.githubusercontent.com/assets/6613013/8706518/2a6ca0fe-2afe-11e5-8582-657c29197bae.png)

**Comment by tshaffe1** [comment]
It kind of works in the `lebedev` branch, but there are still artifacts. The attached image is Lebedev - Gauss for delta initial condition. Lebedev is too hot at the initial point and moving along the axes.

![lg](https://cloud.githubusercontent.com/assets/6613013/8753339/eb1a0162-2c88-11e5-805a-d392265bcd32.png)
